language: generic
cache:
  directories:
    - testcache
notifications:
  email: false
script:
    - cat testcache/shouldbeempty
    - mkdir -p testcache
    - exit 1
    - echo 'THIS SHOULD NOT GET SAVED' > testcache/shouldbeempty
